### ISSUE TITLE
poor annotation at onCancel in the Payment Control

### ISSUE THREAD

**Issue by ondraondra81** [MetisFW/PayPal#2]
annotation say: @var array of callbacks, signature: function(AccountBasedPayPalControl $control, array $response)
https://github.com/MetisFW/PayPal/blob/master/src/MetisFW/PayPal/UI/PaymentControl.php#L34

but it calls only with PaymentControl
https://github.com/MetisFW/PayPal/blob/master/src/MetisFW/PayPal/UI/PaymentControl.php#L84

**Comment by Hajneej** [comment]
Thanks for creating issue. You are completely right. I will fix it

**Comment by MartinMystikJonas** [comment]
Closed by 2d77231
