### ISSUE TITLE
a problem with paypal sdk

### ISSUE THREAD

**Issue by marabucz** [MetisFW/PayPal#5]
There's a slight problem with PayPal SDK as you'll keep getting "SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure" error. A workaround is to modify config.neon settings and add ```
```
    'http.CURLOPT_SSLVERSION': 4
    # 'http.CURLOPT_CONNECTTIMEOUT' => 30
```
row to avoid it. I know it's not really a MetisFW problem, but it might be added into the default configuration.

**Comment by Hajneej** [comment]
First of all, thanks for the usage and the contribution.

I am not sure about the solution. As this blog post says [link](https://devblog.paypal.com/upcoming-security-changes-notice/), PayPal will require using TLS v1.2 in June 2017. So it would be more convenient to set the CURLOPT_SSLVERSION to 6. If I am not missing something, the PayPal API will refuse the connection when you use the CURLOPT_SSLVERSION 4.

But I still think that we should not change the cURL options in the default setup. When you want to connect to PayPal API, you have to have correctly setup and up to date OpenSSL, PHP and curl. Also, if you have up to date OpenSSL/PHP/curl then the client and the server should automatically negotiate the cypher version during the handshake (see [link](https://stackoverflow.com/a/35097466) for more information). These things are out of control from the point of Nette extension. And hardcoding a specific version is not a solution as it can bring confusion.

**Comment by Hajneej** [comment]
I am closing that issue because I think that the answer is sufficient. If you would like to add a comment, please reopen that issue.
